/**
 * Shared company directory normalization for /companies rebuild + page fallbacks.
 */

export function toCompanySlug(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/-+$/, '')
    .replace(/^-+/, '');
}

/** Junk/test company names to exclude entirely */
export const COMPANY_BLOCKLIST = new Set([
  'leverdemo 8',
  'getwingapp',
  'leverdemo',
  'test company',
  'demo company',
  'smart working solutions',
  'confidential',
  '10xteam',
  'careers - think digitally',
  'careers.azx.io',
  'brook hiddink - highticket.io',
  'unknown',
  'n/a',
  'na',
  'none',
  'null',
  'undefined',
  'company',
]);

/** Normalize variant company names to canonical form */
export const COMPANY_NAME_MAP: Record<string, string> = {
  'doordash usa': 'DoorDash',
  doordash: 'DoorDash',
  'shopback 2': 'ShopBack',
  shopback: 'ShopBack',
  'brillio 2': 'Brillio',
  brillio: 'Brillio',
  lyrahealth: 'Lyra Health',
  'lyra health': 'Lyra Health',
  ciandt: 'CI&T',
  'ci&t': 'CI&T',
  'hadrian-automation': 'Hadrian',
  hadrian: 'Hadrian',
  'relativity space': 'Relativity',
  relativity: 'Relativity',
  'scale ai': 'Scale AI',
  scale: 'Scale AI',
  'unity technologies': 'Unity',
  unity: 'Unity',
  'base-power': 'Base Power',
  'heidihealth.com.au': 'Heidi Health',
  'roadsurfer.com': 'Roadsurfer',
  'the-exploration-company': 'The Exploration Company',
  'finni-health': 'Finni Health',
  'apex-technology-inc': 'Apex Technology',
  northwoodspace: 'Northwood Space',
  horizon3ai: 'Horizon3.ai',
  marianaminerals: 'Mariana Minerals',
  'vertical-aerospace': 'Vertical Aerospace',
  'govtech singapore': 'GovTech',
  'govtech ': 'GovTech',
  'amplitude ': 'Amplitude',
  'kraken.com': 'Kraken',
  kraken: 'Kraken',
  'chime financial, inc': 'Chime',
  'gusto, inc.': 'Gusto',
  openai: 'OpenAI',
  airwallex: 'Airwallex',
  snowflake: 'Snowflake',
  deel: 'Deel',
  notion: 'Notion',
  vanta: 'Vanta',
  ramp: 'Ramp',
  cohere: 'Cohere',
  langchain: 'LangChain',
  plaid: 'Plaid',
  perplexity: 'Perplexity',
  replit: 'Replit',
  clickup: 'ClickUp',
  cursor: 'Cursor',
  socure: 'Socure',
  sentry: 'Sentry',
  persona: 'Persona',
  sanity: 'Sanity',
  pleo: 'Pleo',
  sardine: 'Sardine',
  modal: 'Modal',
  drata: 'Drata',
  attio: 'Attio',
  twenty: 'Twenty',
  linear: 'Linear',
  infisical: 'Infisical',
  writer: 'Writer',
  confluent: 'Confluent',
  semgrep: 'Semgrep',
  livekit: 'LiveKit',
  anyscale: 'Anyscale',
  plain: 'Plain',
  column: 'Column',
  unit: 'Unit',
  supabase: 'Supabase',
  render: 'Render',
  trivago: 'trivago',
  oyster: 'Oyster',
  character: 'Character.AI',
  n8n: 'n8n',
  posthog: 'PostHog',
  stream: 'Stream',
  railway: 'Railway',
  mindvalley: 'Mindvalley',
  resend: 'Resend',
  neon: 'Neon',
  statsig: 'Statsig',
  stytch: 'Stytch',
  runway: 'Runway',
  clerk: 'Clerk',
  axiom: 'Axiom',
  inngest: 'Inngest',
  causal: 'Causal',
  doppler: 'Doppler',
  hightouch: 'Hightouch',
  huggingface: 'Hugging Face',
  consensys: 'ConsenSys',
  gopuff: 'Gopuff',
  spotify: 'Spotify',
  deliveroo: 'Deliveroo',
  okta: 'Okta',
  klaviyo: 'Klaviyo',
  robinhood: 'Robinhood',
  jfrog: 'JFrog',
  handshake: 'Handshake',
  palantir: 'Palantir',
  lyft: 'Lyft',
  coinbase: 'Coinbase',
  hostinger: 'Hostinger',
  instacart: 'Instacart',
  remote: 'Remote',
  dropbox: 'Dropbox',
  duolingo: 'Duolingo',
  cribl: 'Cribl',
  databricks: 'Databricks',
  harvey: 'Harvey',
  everai: 'EverAI',
  applied: 'Applied',
  illumio: 'Illumio',
  instructure: 'Instructure',
  deepl: 'DeepL',
  siteminder: 'SiteMinder',
  gamma: 'Gamma',
  lovable: 'Lovable',
  floqast: 'FloQast',
  elfbeauty: 'e.l.f. Beauty',
  swordhealth: 'Sword Health',
  rothys: "Rothy's",
};

export function canonicalizeCompanyName(raw: string): string | null {
  const trimmed = (raw || '').trim();
  if (!trimmed || trimmed.includes('...')) return null;
  const lower = trimmed.toLowerCase();
  if (COMPANY_BLOCKLIST.has(lower)) return null;
  return COMPANY_NAME_MAP[lower] || trimmed;
}
