import fs from 'fs';

const posts = [
  { text: "Quit last night. Made the kids breakfast this morning for the first time in months. Sometimes the best career move is just walking away. Start fresh at cvin.bio/jobs", img: "viral3/v3_00_291892.jpg" },
  { text: "That look when your boss realizes you actually have options. Find yours at cvin.bio/jobs", img: "viral3/v3_01_181254.jpg" },
  { text: "Why is this so painfully accurate though. If it hits too close to home, maybe browse cvin.bio/jobs", img: "viral3/v3_02_169608.jpg" },
  { text: "They threw a surprise party after being told not to, then fired the person for their reaction. You literally cannot make this up. Better workplaces exist at cvin.bio/jobs", img: "viral3/v3_03_163303.jpg" },
  { text: "This company sent a rejection email with the ChatGPT prompt still in it. Could not even be bothered to proofread the rejection. Companies that actually care are hiring at cvin.bio/jobs", img: "viral3/v3_04_159516.png" },
  { text: "Still processing this one honestly. If your workplace looks anything like this, worth checking cvin.bio/jobs", img: "viral3/v3_05_145650.jpg" },
  { text: "Some headlines just state what literally everyone already knows. Real talk and real jobs at cvin.bio/jobs", img: "viral3/v3_06_145322.jpg" },
  { text: "\"I quit 👍\" — possibly the most satisfying two-word text ever sent to a bad manager. For what comes next, there is always cvin.bio/jobs", img: "viral3/v3_07_140588.jpg" },
  { text: "\"Nobody wants to work anymore.\" Ok but have you tried not making the job miserable? Companies that get it are hiring at cvin.bio/jobs", img: "viral3/v3_08_138716.jpg" },
  { text: "\"Saved $100k by 27\" — turns out mom covered $140k in tuition. Real opportunities without the trust fund at cvin.bio/jobs", img: "viral3/v3_09_137240.jpg" },
  { text: "More of this energy in every workplace please. Find teams that actually get it at cvin.bio/jobs", img: "viral3/v3_11_133696.jpg" },
  { text: "This one hit different honestly. If it resonates, worth browsing cvin.bio/jobs", img: "viral3/v3_12_130002.jpg" },
  { text: "The gift that keeps on giving — and not in a good way. Escape the cycle at cvin.bio/jobs", img: "viral3/v3_13_125463.jpg" },
  { text: "Why indeed. Better questions deserve better answers, and better jobs are at cvin.bio/jobs", img: "viral3/v3_14_124758.jpg" },
  { text: "Rotten to the core and they still wonder why people leave. Something worth staying for at cvin.bio/jobs", img: "viral3/v3_15_123857.jpg" },
  { text: "Your free time is yours. Protect it. Find roles that actually respect that at cvin.bio/jobs", img: "viral3/v3_16_120471.jpg" },
  { text: "People want to work. They just do not want to destroy themselves for rent money. Fair pay and real roles at cvin.bio/jobs", img: "viral3/v3_17_119243.jpg" },
  { text: "\"Probably getting fired for this.\" Honestly? Respect. Land somewhere better at cvin.bio/jobs", img: "viral3/v3_18_119139.jpg" },
  { text: "Someone at work put a \"help yourself\" note on snacks a colleague bought with their own money. The audacity. Better offices exist at cvin.bio/jobs", img: "viral3/v3_19_118520.jpeg" },
  { text: "Gen Z will not apply if the salary is not listed, and honestly good for them. Transparent listings at cvin.bio/jobs", img: "viral3/v3_20_117451.jpg" },
  { text: "Same job, same company. He gets four pockets, she gets zero. Even the uniforms are not equal. Companies doing better at cvin.bio/jobs", img: "viral3/v3_21_116888.jpeg" },
  { text: "Nobody explains how this actually works and it shows. What does work though? Jobs at cvin.bio/jobs", img: "viral3/v3_22_116139.jpg" },
  { text: "Spend your whole salary paying off the degree that got you that salary. Make it make sense. Or just make a move at cvin.bio/jobs", img: "viral3/v3_23_115230.jpg" },
  { text: "A $0.25 raise this year while the boss pulled up in a Ferrari. The math is not mathing. Know your worth at cvin.bio/jobs", img: "viral3/v3_24_115068.jpg" },
  { text: "Could not have said it better honestly. If this hits home, cvin.bio/jobs has roles worth looking at", img: "viral3/v3_25_114648.jpg" },
  { text: "This energy right here. Know your worth, then go prove it at cvin.bio/jobs", img: "viral3/v3_26_114230.jpg" },
  { text: "When your friend finally leaves that toxic job and you could not be prouder. Help someone make that move with cvin.bio/jobs", img: "viral3/v3_27_113256.jpg" },
  { text: "Manager: \"Just cleaned up the code a little.\" The codebase after: absolute chaos. Dev roles that make sense at cvin.bio/jobs", img: "viral3/v3_28_112995.png" },
  { text: "Someone please make this into an actual show. Everyone would binge it in one sitting. Until then, there is cvin.bio/jobs", img: "viral3/v3_29_112773.jpg" },
  { text: "Probably the most realistic take on modern work out there. Ready for something different? cvin.bio/jobs", img: "viral3/v3_30_110967.jpg" },
  { text: "Leadership really thinks pizza fixes burnout. Places that actually value people are hiring at cvin.bio/jobs", img: "viral3/v3_31_110749.jpg" },
  { text: "Finally someone asking the real question. Real answers and real jobs at cvin.bio/jobs", img: "viral3/v3_32_110745.jpg" },
  { text: "\"You are short staffed and need someone tomorrow? That will be $39.75 an hour.\" Legendary negotiation. More power moves start at cvin.bio/jobs", img: "viral3/v3_33_107059.jpg" },
  { text: "The satisfaction of seeing this is honestly unmatched. Find that kind of energy in your next role at cvin.bio/jobs", img: "viral3/v3_34_106969.png" },
  { text: "Imagine treating employees like this and wondering why nobody stays. Companies actually worth staying at are on cvin.bio/jobs", img: "viral3/v3_35_104575.jpeg" },
  { text: "Love to see it. More wins like this start at cvin.bio/jobs", img: "viral3/v3_36_103729.jpg" },
  { text: "Thoughts on this one? Because there are several. Share yours and browse roles at cvin.bio/jobs", img: "viral3/v3_37_102239.jpg" },
  { text: "Manager said throw the cookies away but also said nobody can take them home. Make it make sense. Sane workplaces at cvin.bio/jobs", img: "viral3/v3_38_90285.png" },
  { text: "Manager took five people out as a \"treat\" and bought one of these. The appreciation budget was apparently $3. Employers who actually try at cvin.bio/jobs", img: "viral3/v3_39_86832.jpeg" },
  { text: "Most popular LinkedIn profile today and honestly, fair enough. Build yours and find roles at cvin.bio/jobs", img: "viral3/v3_40_83623.jpeg" },
  { text: "\"It was just a prank.\" No it was not, and everyone knew that. Professional workplaces at cvin.bio/jobs", img: "viral3/v3_41_79086.jpeg" },
  { text: "It is called a vacation. Not PTO. Not a \"personal wellness day.\" Vacation. Jobs that respect time off at cvin.bio/jobs", img: "viral3/v3_42_75761.jpeg" },
  { text: "Job listing wants 10 years of experience in something that has existed for 3 years. Sure. Realistic listings at cvin.bio/jobs", img: "viral3/v3_43_72269.jpeg" },
  { text: "The streets have literally spoken on this one. Hear them out and check cvin.bio/jobs", img: "viral3/v3_44_66104.jpeg" },
  { text: "The audacity of this email is genuinely impressive. Companies that communicate like humans at cvin.bio/jobs", img: "viral3/v3_45_65657.jpeg" },
  { text: "Red flags everywhere. If your company looks like this, it is time to leave. Start fresh at cvin.bio/jobs", img: "viral3/v3_46_49599.jpeg" },
  { text: "Do you agree with this? Because roughly 300,000 people on Reddit do. Find your next role at cvin.bio/jobs", img: "viral3/v3_47_49097.jpeg" },
  { text: "\"Write clean code,\" they said. \"It will be beautiful,\" they said. Dev roles where that is actually possible at cvin.bio/jobs", img: "viral3/v3_48_49063.jpeg" },
  { text: "Got CC'd on the internal email explaining the rejection. Companies are literally not even trying anymore. Ones that do are at cvin.bio/jobs", img: "viral3/v3_49_44214.jpeg" },
  { text: "Gates and Jobs came and went, but the developer who actually wrote the code? Timeless. Find your next chapter at cvin.bio/jobs", img: "viral3/v3_50_41339.jpeg" },
  { text: "Code before AI versus code after AI. Somehow both are broken. Dev jobs that actually make sense at cvin.bio/jobs", img: "viral3/v3_51_40910.jpeg" },
  { text: "Boss went to Europe two days ago and is already sending panic emails. Some people literally cannot unplug. Healthy workplaces at cvin.bio/jobs", img: "viral3/v3_52_38214.jpeg" },
  { text: "The OpenToWork badge should not be something people are ashamed of. Own it and find what is next at cvin.bio/jobs", img: "viral3/v3_53_37439.png" },
  { text: "When will they get it? They will not, at least not until everyone has already left. Do not wait around, check cvin.bio/jobs", img: "viral3/v3_54_37292.jpeg" },
  { text: "Painfully accurate about today's job market. Something better is out there at cvin.bio/jobs", img: "viral3/v3_55_37245.jpeg" },
  { text: "CEO delusion is at an all-time high meanwhile the team holding everything together gets a thank you email. Teams that get real recognition at cvin.bio/jobs", img: "viral3/v3_56_36793.jpeg" },
  { text: "OG developers built entire apps with Notepad and sheer willpower. Respect. Carry that energy into your next role at cvin.bio/jobs", img: "viral3/v3_57_36263.jpeg" },
  { text: "Seven rounds of interviews just to get ghosted. The disrespect is real. Hiring that respects your time at cvin.bio/jobs", img: "viral3/v3_58_36158.jpeg" },
  { text: "Imagine getting added to your own rejection email thread. You literally cannot make this up. Competent employers at cvin.bio/jobs", img: "viral3/v3_59_35601.jpeg" },
  { text: "\"Works on my machine\" — the universal developer escape card. Find a team that actually tests together at cvin.bio/jobs", img: "viral3/v3_60_34864.jpeg" },
];

console.log(`Total posts: ${posts.length}`);
fs.writeFileSync('scratch/final_60_posts.json', JSON.stringify(posts, null, 2));
console.log('Saved');
